import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { supabase } from '../../config/supabase';
import { LogOut, ScanLine, ListOrdered, Navigation, Package, Search, MapPin, Loader2, Info } from 'lucide-react';
import toast from 'react-hot-toast';

const SharedDashboard = ({ roleType }) => {
  const { user, role, logout } = useAuth();
  const [activeTab, setActiveTab] = useState('scan');
  
  // Scan State
  const [traceId, setTraceId] = useState('');
  const [searchLoading, setSearchLoading] = useState(false);
  const [product, setProduct] = useState(null);
  const [alerts, setAlerts] = useState([]);
  
  // Log Event State
  const [eventData, setEventData] = useState({
    location: '', temperature: '', humidity: '', notes: ''
  });
  const [locationLoading, setLocationLoading] = useState(false);
  const [logLoading, setLogLoading] = useState(false);

  // My Events State
  const [myEvents, setMyEvents] = useState([]);

  // Auto-set Stage mapping
  const roleStageMap = {
    processor: 'processing',
    distributor: 'distribution',
    retailer: 'retail'
  };
  const myStage = roleStageMap[roleType] || 'consumer';

  useEffect(() => {
    if (activeTab === 'events') fetchMyEvents();
  }, [activeTab]);

  const fetchMyEvents = async () => {
    try {
      const { data, error } = await supabase
        .from('supply_chain_events')
        .select(`*, product:products(name)`)
        // Filter by events generated by this actor email (or lookup by users_extended if needed)
        // For simplicity, we just fetch events where actor is user's display name or email
        // Or we can fetch all and filter client side.
        .order('created_at', { ascending: false });
        
      if (!error && data) setMyEvents(data);
    } catch (err) {
      console.error(err);
    }
  };

  const handleSearch = async (e) => {
    e.preventDefault();
    if (!traceId) return;
    setSearchLoading(true);
    try {
      const res = await fetch(`http://localhost:5000/api/products/${traceId}`);
      if (!res.ok) throw new Error('Product not found');
      const data = await res.json();
      setProduct(data.product);

      // Fetch active alerts for AI Insight Box
      const { data: productAlerts } = await supabase
        .from('alerts')
        .select('*')
        .eq('product_id', data.product.id)
        .eq('resolved', false);
      setAlerts(productAlerts || []);

    } catch (err) {
      toast.error(err.message);
      setProduct(null);
    }
    setSearchLoading(false);
  };

  const getLocation = () => {
    setLocationLoading(true);
    navigator.geolocation.getCurrentPosition(
      async (position) => {
        const { latitude, longitude } = position.coords;
        try {
          const res = await fetch(`https://nominatim.openstreetmap.org/reverse?lat=${latitude}&lon=${longitude}&format=json`);
          const data = await res.json();
          const city = data.address.city || data.address.state_district || data.address.state;
          setEventData(prev => ({ ...prev, location: city }));
        } catch (error) {}
        setLocationLoading(false);
      },
      () => setLocationLoading(false)
    );
  };

  const handleLogEvent = async (e) => {
    e.preventDefault();
    setLogLoading(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const payload = {
        product_id: product.id,
        stage: myStage,
        role: roleType,
        actor: user.user_metadata?.display_name || user.email,
        ...eventData
      };

      const res = await fetch('http://localhost:5000/api/events/log', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.access_token}`
        },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      
      toast.success(`Event logged! Hash: ${data.event_hash.substring(0, 10)}...`);
      setEventData({ location: '', temperature: '', humidity: '', notes: '' });
      setProduct(null);
      setTraceId('');
    } catch (err) {
      toast.error(err.message);
    }
    setLogLoading(false);
  };

  return (
    <div className="flex min-h-screen bg-slate-900">
      {/* Sidebar */}
      <div className="w-64 bg-slate-800 border-r border-slate-700 flex flex-col">
        <div className="p-6 border-b border-slate-700">
          <h2 className="text-xl font-bold flex items-center gap-2 text-orange-500"><Navigation className="w-6 h-6" /> TraceChain</h2>
        </div>
        <nav className="flex-1 p-4 space-y-2">
          <button 
            onClick={() => setActiveTab('scan')} 
            className={`w-full text-left px-4 py-3 rounded-lg font-medium flex items-center gap-3 transition-colors ${activeTab === 'scan' ? 'bg-orange-500/10 text-orange-500' : 'text-slate-300 hover:bg-slate-700/50'}`}
          >
            <ScanLine className="w-5 h-5" /> Scan Product
          </button>
          <button 
            onClick={() => setActiveTab('events')} 
            className={`w-full text-left px-4 py-3 rounded-lg font-medium flex items-center gap-3 transition-colors ${activeTab === 'events' ? 'bg-orange-500/10 text-orange-500' : 'text-slate-300 hover:bg-slate-700/50'}`}
          >
            <ListOrdered className="w-5 h-5" /> My Events
          </button>
        </nav>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex flex-col">
        {/* Header */}
        <header className="h-20 border-b border-slate-700 px-8 flex items-center justify-between bg-slate-800/50">
          <div className="flex items-center gap-4">
            <h1 className="text-xl font-semibold capitalize">{roleType} Dashboard</h1>
            <span className="px-3 py-1 bg-slate-700 rounded-full text-xs font-mono text-slate-300 uppercase">{role}</span>
          </div>
          <div className="flex items-center gap-6">
            <span className="text-sm font-medium text-slate-300">{user?.email}</span>
            <button onClick={logout} className="p-2 text-slate-400 hover:text-red-400 transition-colors">
              <LogOut className="w-5 h-5" />
            </button>
          </div>
        </header>

        {/* Content */}
        <main className="p-8 flex-1 overflow-auto">
          {activeTab === 'scan' && (
            <div className="max-w-4xl mx-auto space-y-8">
              
              <div className="bg-slate-800 p-6 rounded-2xl border border-slate-700 shadow-lg">
                <h2 className="text-lg font-bold mb-4 flex items-center gap-2"><ScanLine className="text-orange-500" /> Lookup & Scan Product</h2>
                <form onSubmit={handleSearch} className="flex gap-4">
                  <div className="relative flex-1">
                    <Search className="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" />
                    <input 
                      type="text" 
                      placeholder="Enter Trace ID (e.g. TC-2026-FOOD-001)" 
                      value={traceId}
                      onChange={e => setTraceId(e.target.value)}
                      className="w-full bg-slate-900 border border-slate-700 focus:border-orange-500 rounded-lg py-3 pl-12 pr-4 transition-colors font-mono uppercase"
                    />
                  </div>
                  <button type="submit" disabled={searchLoading} className="bg-orange-500 hover:bg-orange-600 text-white px-8 rounded-lg font-medium transition-colors flex items-center justify-center min-w-[120px]">
                    {searchLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : 'Search'}
                  </button>
                </form>
              </div>

              {product && (
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                  {/* Product Info & Alert Col */}
                  <div className="md:col-span-1 space-y-6">
                    <div className="bg-slate-800 p-6 rounded-2xl border border-slate-700">
                      <div className="flex items-center gap-3 mb-4">
                        <Package className="w-8 h-8 text-orange-500" />
                        <div>
                          <h3 className="font-bold text-lg">{product.name}</h3>
                          <p className="font-mono text-xs text-orange-400">{product.id}</p>
                        </div>
                      </div>
                      <div className="space-y-3 text-sm text-slate-300">
                        <div className="flex justify-between border-b border-slate-700 pb-2">
                          <span className="text-slate-500">Origin</span>
                          <span className="font-medium text-right">{product.origin}</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-700 pb-2">
                          <span className="text-slate-500">Current Stage</span>
                          <span className="font-medium capitalize text-right">{product.current_stage}</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-700 pb-2">
                          <span className="text-slate-500">Trust Score</span>
                          <span className={`font-bold text-right ${product.trust_score > 80 ? 'text-green-500' : product.trust_score > 50 ? 'text-yellow-500' : 'text-red-500'}`}>
                            {product.trust_score}/100
                          </span>
                        </div>
                        <div className="flex justify-between pb-2">
                          <span className="text-slate-500">Expiry</span>
                          <span className="font-medium text-right">{new Date(product.exp_date).toLocaleDateString()}</span>
                        </div>
                      </div>
                    </div>

                    {alerts.length > 0 && (
                      <div className="bg-red-500/10 border border-red-500/50 p-5 rounded-2xl">
                        <h4 className="flex items-center gap-2 font-bold text-red-400 mb-3"><Info className="w-5 h-5" /> AI Insight Alerts</h4>
                        <ul className="space-y-2">
                          {alerts.map(a => (
                            <li key={a.id} className="text-sm text-red-300 flex items-start gap-2">
                              <span className="mt-1 w-1.5 h-1.5 rounded-full bg-red-400 shrink-0"></span>
                              {a.message}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>

                  {/* Log Event Form */}
                  <div className="md:col-span-2 bg-slate-800 p-8 rounded-2xl border border-slate-700 shadow-lg">
                    <div className="mb-6 pb-6 border-b border-slate-700 flex justify-between items-end">
                      <div>
                        <h2 className="text-xl font-bold mb-1 flex items-center gap-2">Log New Event</h2>
                        <p className="text-sm text-slate-400">Appending cryptographically secure block for <strong className="text-orange-400 uppercase">{myStage}</strong> stage.</p>
                      </div>
                    </div>

                    <form onSubmit={handleLogEvent} className="space-y-6">
                      <div className="grid grid-cols-2 gap-6">
                        <div className="col-span-2 flex gap-4">
                          <div className="flex-1">
                            <label className="block text-sm font-medium text-slate-300 mb-1">Actor Name</label>
                            <input disabled value={user?.user_metadata?.display_name || user?.email} className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 opacity-70 cursor-not-allowed text-orange-200" />
                          </div>
                          <div className="flex-1">
                            <label className="block text-sm font-medium text-slate-300 mb-1">Location</label>
                            <div className="flex">
                              <input required value={eventData.location} onChange={e => setEventData({...eventData, location: e.target.value})} className="w-full bg-slate-900 border border-slate-700 rounded-l-lg px-4 py-3" />
                              <button type="button" onClick={getLocation} className="bg-slate-700 px-4 rounded-r-lg border border-l-0 border-slate-700">
                                {locationLoading ? <Loader2 className="w-5 h-5 animate-spin text-slate-300" /> : <MapPin className="w-5 h-5 text-slate-300" />}
                              </button>
                            </div>
                          </div>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-slate-300 mb-1">Temperature (°C) <span className="text-slate-500 font-normal">(Optional)</span></label>
                          <input type="number" step="0.1" value={eventData.temperature} onChange={e => setEventData({...eventData, temperature: e.target.value})} className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-slate-300 mb-1">Humidity (%) <span className="text-slate-500 font-normal">(Optional)</span></label>
                          <input type="number" step="0.1" value={eventData.humidity} onChange={e => setEventData({...eventData, humidity: e.target.value})} className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3" />
                        </div>
                        <div className="col-span-2">
                          <label className="block text-sm font-medium text-slate-300 mb-1">Notes / Condition</label>
                          <textarea rows="3" value={eventData.notes} onChange={e => setEventData({...eventData, notes: e.target.value})} className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3"></textarea>
                        </div>
                      </div>
                      
                      <div className="flex justify-end pt-4">
                        <button type="submit" disabled={logLoading} className="bg-orange-500 hover:bg-orange-600 px-8 py-3 rounded-lg font-medium text-white transition-colors flex items-center justify-center min-w-[200px] shadow-lg shadow-orange-500/20">
                          {logLoading ? <Loader2 className="animate-spin w-5 h-5" /> : 'Log Event to Blockchain'}
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              )}
            </div>
          )}

          {activeTab === 'events' && (
            <div className="bg-slate-800 rounded-2xl border border-slate-700 overflow-hidden shadow-xl">
              {myEvents.length === 0 ? (
                <div className="p-12 text-center text-slate-400">No events logged yet.</div>
              ) : (
                <table className="w-full text-left text-sm text-slate-300">
                  <thead className="bg-slate-900/50 text-slate-400 font-semibold uppercase text-xs">
                    <tr>
                      <th className="px-6 py-4">Product</th>
                      <th className="px-6 py-4">Stage Logged</th>
                      <th className="px-6 py-4">Location</th>
                      <th className="px-6 py-4">Timestamp</th>
                      <th className="px-6 py-4">Block Hash</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-700/50">
                    {myEvents.map(ev => (
                      <tr key={ev.id} className="hover:bg-slate-700/30 transition-colors">
                        <td className="px-6 py-4 font-medium text-white">{ev.product?.name || ev.product_id}</td>
                        <td className="px-6 py-4 capitalize"><span className="bg-slate-700 text-slate-200 px-2 py-1 rounded text-xs">{ev.stage}</span></td>
                        <td className="px-6 py-4">{ev.location}</td>
                        <td className="px-6 py-4 text-slate-400">{new Date(ev.created_at).toLocaleString()}</td>
                        <td className="px-6 py-4 font-mono text-xs text-orange-400/80 max-w-[150px] truncate" title={ev.event_hash}>{ev.event_hash}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          )}
        </main>
      </div>
    </div>
  );
};

export default SharedDashboard;
